#!/usr/bin/env bash

set -euo pipefail

if [[ -d src/ ]]; then

  printf "Building src/\n"

  mkdir -p dst/lib/

  find src/ -type f -name "*.java" -exec javac -cp "dst/lib/*" -d dst/lib/ '{}' +

  jar cf dst/lib/mywebsiteappcontainer.jar -C dst/lib/ com/

  rm -r dst/lib/com/

fi

printf "Done\n"

