#!/usr/bin/env bash

set -euo pipefail

if [[ -d src/ ]]; then

  find src/ -type f -name "*.java" -exec javac -cp "dst/*" -d dst/ '{}' +

  jar cf dst/mywebsitecontainer.jar -C dst/ com/

  rm -r dst/com/

fi

