#!/usr/bin/env bash

set -euo pipefail

if [[ -d src/ ]]; then

  find src/ -type f -name "*.java" -exec javac -cp "dst/*" -d dst/mywebsiteengine/ '{}' +

  jar cf dst/mywebsiteengine.jar -C dst/mywebsiteengine/ ./

  rm -r dst/mywebsiteengine/

fi

